### PR TITLE
Allow dns_owner user to read and write dns directory

### PR DESCRIPTION
**Pull request by BenWaller**
---
name: Allow dns_owner user to read and write dns directory
about: The dns_owner is not the owner of the dns_confdir. The bind9 service will not start up unless it has write access to that directory. 

---

### CODE REVIEW

**Comment by robertdebock** [comment]
Cool, there is a [minor error in there](https://travis-ci.org/robertdebock/ansible-role-dns/jobs/489166351#L671), let me see if I can fix this for you:
```
    /home/travis/build/robertdebock/ansible-role-dns/handlers/main.yml
      19:18     error    no new line character at the end of file  (new-line-at-end-of-file)
```

**Comment by robertdebock** [comment]
Next challenge is [this error](https://travis-ci.org/robertdebock/ansible-role-dns/jobs/489187488#L870):

```
PermissionError: [Errno 1] Operation not permitted: b'/etc/../proc/self/mounts
```

I guess that some file in `dns_confdir` (for Archlinux `/etc` (see `vars/main.yml`.)) links back to /proc.

The `recurse` may be an issue, it can also be that Archlinux just has an issue, with or without this role.

I'll inspect a little better later.

Thanks for the feedback @BenWaller !

**Comment by robertdebock** [comment]
Hm, so the permission-handler sets too many permissions, causing issues on the next Ansible run.

Can we go back to the original issue. I'd like to reproduce the issue you were seeing. Can you give me a little more details on the operating system you saw this issue on?

**Comment by BenWaller** [comment]
The  recursive permission change might be a bit of overkill for the situation. I'm running the role like this on Ubuntu 18.04
```
- hosts: dnsservers
  become: true 
  remote_user: myadmin
  tasks:

    - import_role:
        name: robertdebock.dns
```

I've tried running with just the default variables to see if it works. If I don't use become:true, then apt can't install what it needs to. If I don't adjust the permissions of the bind directory I get the 

failed: [primary] (item=mydomain.com) => {"changed": false, "checksum": "ac0678bd3ae1842b884c4e854d5a713479175f9d", "item": {"mx": [{"name": "mail1.mydomain.com.", "priority": 10}, {"name": "mail2.mydomain.com.", "priority": 20}], "name": "mydomain.com", "records": [{"name": "demo-elastic", "value": "10.5.2.254"}, {"name": "demo-logs", "value": "10.5.2.254"}, {"name": "demo-elastic-apps", "value": "10.5.2.254"}], "ttl":604800}, "msg": "Destination /etc/bind not writable"}

I then tried changing the owner of the confdir and datadir when they're created instead of changing everything in the directory. This worked for me and might be a solution with fewer side effects.

**Comment by robertdebock** [comment]
Good information, I'll try a few scenarios on Ubuntu 18.04. I'll get back to you later.

**Comment by robertdebock** [comment]
I think I found the issue; the `dns_datadir` (where zone-files were saved) was set to `/etc/bind`. Apparmor allows zonefiles in `/var/lib/bind`. (See `/etc/apparmor.d/usr.sbin.named`.)

```
  # /etc/bind should be read-only for bind
  # /var/lib/bind is for dynamically updated zone (and journal) files.
  # /var/cache/bind is for slave/stub data, since we're not the origin of it.
  # See /usr/share/doc/bind9/README.Debian.gz
  /etc/bind/** r,
  /var/lib/bind/** rw,
  /var/lib/bind/ rw,
```

So, basically zone files need to end up in `/var/lib/bind`.

I changed the role, `var/main.yml` now contains:
```
_dns_datadir:
  default: /var/named
  # Debian: /etc/bind
  Debian: /var/lib/bind
  # Ubuntu: /etc/bind
  Ubuntu: /var/lib/bind
  openSUSE Leap: /var/lib/named/var/named
  openSUSE Tumbleweed: /var/lib/named/var/named
```

I'm testing the role locally now and will commit-push when tests succeed.

Thanks a lot for your feedback @BenWaller, this help me learn and improve the quality of this role!

**Comment by robertdebock** [comment]
Just before this code-change, I've done changes to all roles, so the building/testing queue is quite long. I expect the tests to be done Saturday, release on Sunday. Bit of an estimation though.

**Comment by robertdebock** [comment]
The fix has been released in the latest version. Please test and let me know if this resolves your problem.

Thanks again for you feedback.

**Comment by robertdebock** [comment]
I'll close this merge request, as the issue has been solved in a previous release, thanks for your help!

**Comment by BenWaller** [comment]
I tested out your new solution and it worked. Thanks.

**Pull request closed without merging**
